source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NOTIFIT-Swift_Example', :exclusive => true do
  pod 'NOTIFIT-Swift', :path => '../Pod/Classes'
end

target 'NOTIFIT-Swift_Tests', :exclusive => true do
  pod 'NOTIFIT-Swift', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end
